package com.lab_program;

import java.util.Random;

class Thread3 implements Runnable {
    public int num;
    public Thread3 (int num) {
        this.num=num;
    }
    public void run() {
        System.out.println("Cube of " + num + " is : " + num*num*num);
    }
}
class Thread2 implements Runnable {
    public int num;
    public Thread2 (int num) {
        this.num=num;
    }
    public void run() {
        System.out.println("Square of " + num + " is : " + num*num);
    }
}
class Thread1 extends Thread
{
    public void run() {
        int num;
        Random rand = new Random();
        try{
            for(int i=0;i<100;i++) {
                num = rand.nextInt(100);
                System.out.println("Number generated by thread 1 : " + num);
                Thread t2 = new Thread(new Thread2 (num));

                t2.start();
                Thread t3 = new Thread (new Thread3(num));

                t3.start();
                Thread.sleep(1000);
                System.out.println();
            }
        }
        catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }
}
public class MultiThreadingProg {

    public static void main(String[] args ){

        Thread1 firstThread = new Thread1();
        Thread t1 = new Thread (firstThread);
        t1.start();

    }
}
